<?php $preference=$this->getPreferences()?>
<div class="welcome-msg">
    <h1><?php echo $this->__('MY SKINCARE PREFERENCES - SAVED') ?></h1>
    <p>
    <?php echo $this->__('Thank you for saving your skincare preferences, this will help us offer you more tailored advice and support. Your insights will also help us decide what new additions we can bring to the Aurelia Probiotic Skincare range!') ?>
    </p>
    
    <p>
    <?php echo $this->__('Please call the Aurelia office for a personalised skincare consultation to address any concerns you might have, we are available from Monday - Friday 9am - 5pm GMT  +44 (0)207 751 0022 or email us at info@aureliaskincare.com') ?>
    </p>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <div class="preferences-left">
        <div class="fieldset">
            <ul class="form-list">
                <li>
                    <label for="primary_concern" class="required"><?php echo $this->__('Your primary skin concern is:') ?></label>
                    <div class="input-box">
                        <?php echo $preference->getData('primary_concern_text'); ?>
                    </div>
                </li>
                <li>
                    <label for="secondary_concern" class="required"><?php echo $this->__('Your secondary skin concern is:') ?></label>
                    <div class="input-box">
                        <?php echo $preference->getData('secondary_concern_text'); ?>
                    </div>
                </li>
                <li>
                    <label for="other_brands" ><?php echo $this->__('Other skincare brands & products you love') ?></label>
                    <div class="input-box">
                    <?php echo nl2br($preference->getOtherBrands())?>
                    </div>
                </li>
                <li>
                    <label >
                    <?php echo $this->__('Do you find labels hard to read?') ?>
                    </label>
                    <div class="input-box">
					<ul>
					<li>
                    <div class="checker">
                     <?php echo   $preference->getData('has_glasses_text') ?>
                    </div>
					</li>
					</ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="preferences-right">
        <div class="fieldset">
            <ul class="form-list">
                <li>
                    <label for="skin_care"><?php echo $this->__('What is important to you when you choosing your skincare:') ?></label>
                    <br/><br/>
                    <div class="input-box">
                    <?php
                    $i=0;
		    $options=$preference->getData('skincare_options');
                    $options=is_array($options)?$options:array();
                    foreach($options as $option)
                    {
					?>
                    <div class="checker-main">
                    <label><?php echo $option['label']?></label>
                    </div>
                    <?php } ?>
                    </div>
                </li>
                 <li>
                    <label for="aurelia_feedback" ><?php echo $this->__('Your feedback and suggestions:') ?></label>
                    <div class="input-box">
                    <?php echo nl2br($preference->getAureliaFeedback())?>
                    </div>
                </li>
                <li>
                    <button class="button" onclick="location.href='<?php echo $this->getUrl('preferences/index/edit')?>'"><span><span><?php echo $this->__('EDIT MY PREFERENCES')?></span></span></button>
                </li>
            </ul>
        </div>
    </div>
