<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<div class="block block-blog block-blog-text">
	<?php if ($title = $this->getTitle()): ?>
		<div class="block-title">
			<strong><span><?php echo $this->__($title) ?></span></strong>
		</div>
	<?php endif; ?>
	<div class="block-content">
		<?php echo $this->getText() ?>
	</div>
</div>


<?php if($title=="Aurelia Event" || $title=="Aurelia Events"){

// $username = "AureliaSkincare";
// $limit = 5;

 $_helper = Mage::helper('wordpress/twitter')->getTweets();
 ?>
 
<div class="block block-blog block-blog-tweets">
<div class="block-title">
			<span><?php echo $this->__('tweets') ?></span>
		</div>
<?php 
foreach($_helper as $tweetrersult)
 {

    if (isset($tweetrersult->text)){ ?>
	<?php $tweetUrl =$tweetrersult->entities->media[0]->url; 
				if($tweetUrl==""){
				$tweetUrl= "https://twitter.com/aureliaskincare";
				}
	?>
		<div class="block-content">
		<a target="_blank" href="<?php echo $tweetUrl; ?>"> <?php echo $tweetrersult->text; ?></a>
		</div>
		<?php 	}
	
	}
	
	?>
	
	</div>
	<?php 
   
   }
 ?>