<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php if ($post): ?>
<p class="post-meta details">
<ul class="BlogsharePost">
	<li>Share Post:</li>
	
    <?php $skinUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>
    <!--li><a href="http://www.facebook.com/AureliaProbioticSkincare" target="_blank"><img src="<?php echo $skinUrl."frontend/base/default/images/blog-facebook-icon.png"; ?>"></a></li>
    <li><a href="https://twitter.com/AureliaSkincare" target="_blank"><img src="<?php echo $skinUrl."frontend/base/default/images/blog-twitter-icon.png"; ?>"></a></a></li>
    <li><a href="mailto:info@aureliaskincare.com"><img src="<?php echo $skinUrl."frontend/base/default/images/blog_email_icon.png"; ?>"></a></a></li-->


<li><span class='st_facebook_large' displayText='Facebook'></span></li>
<li><span class='st_twitter_large' displayText='Tweet'></span></li>
<li><span class='st_email_large' displayText='Email'></span></li>
</ul>

<?php if ($this->hasTags($post)): ?>
	<?php // echo stripslashes($this->__('This entry was posted in %s and tagged %s on %s<span class=\"by-author\"> by %s</span>.', $this->getCategoryString($post), $this->getTagString($post), $post->getPostDate(), $post->getAuthor()->getDisplayName())) ?>
<?php else: ?>
	<?php // echo stripslashes($this->__('This entry was posted in %s on %s<span class=\"by-author\"> by %s</span>.', $this->getCategoryString($post), $post->getPostDate(), $post->getAuthor()->getDisplayName())) ?>
<?php endif; ?>
<?php if ($this->canDisplayPreviousNextLinks()): ?>
<span class="post-skips">
	<?php if (($previous = $post->getPreviousPost()) !== false): ?>
		<a href="<?php echo $previous->getPermalink() ?>" class="post-skip post-skip-previous" title="<?php echo $this->escapeHtml($previous->getPostTitle()) ?>">&lt;&nbsp;&nbsp; <?php echo $this->__('Previous Post') ?></a>
	<?php endif; ?>
	<?php if (($next = $post->getNextPost()) !== false): ?>
		<a href="<?php echo $next->getPermalink() ?>" class="post-skip post-skip-next right" title="<?php echo $this->escapeHtml($next->getPostTitle()) ?>"><?php echo $this->__('Next Post') ?>&nbsp;&nbsp; &gt;</a>
	<?php endif; ?>
</span>
<?php endif; ?>
</p>
<?php endif; ?>