
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>js/jquery/cloud-zoom.1.0.2.js"></script>
  
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $videoLink = $_product->getVideolink();
    $_lightboxConfig = Mage::getStoreConfig('easy_lightbox/general');
    /* Main Image Size */
    if (strstr($_lightboxConfig['mainImageSize'], '_')) {
        $mainImageSize = explode('_', $_lightboxConfig['mainImageSize'], 2);
    } else {
        $mainImageSize = array(265, 265);
    }
    /* Popup Image Size */
    if (strstr($_lightboxConfig['popupImageSize'], '_')) {
        $popupImageSize = explode('_', $_lightboxConfig['popupImageSize'], 2);
    } else {
        $popupImageSize = array(0, 0);
    } 
    /* Additional Images Size */
    if (strstr($_lightboxConfig['additionalImageSize'], '_')) {
        $additionalImageSize = explode('_', $_lightboxConfig['additionalImageSize'], 2);
    } else {
        $additionalImageSize = array(60, 60);
    }
    
    $image = $this->helper('catalog/image')->init($_product, 'image');
    if ($popupImageSize[0] > 0) {
        $image = $this->helper('catalog/image')->init($_product, 'image')->resize($popupImageSize[0], $popupImageSize[1]);
    }
       
?>

<?php if(!$_lightboxConfig['defaulzoom']): ?>

<?php
	$maintitle = $this->htmlEscape($_product->getImageLabel());
	if(($_lightboxConfig['productName'] != 0) && empty($maintitle)):
	        $maintitle  = $_product->getName();
	endif;
?>

<?php //if ($_SERVER['REMOTE_ADDR'] == '81.136.239.84'){ ?>
	
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(700); ?>" class="cloud-zoom" id="zoom1" rel="showTitle:false, zoomHeight:285, zoomWidth:285">
        <img title="<?php echo $this->htmlEscape($this->getImageLabel()); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel()); ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(357); ?>" align="left" />
    </a>
    
    
	<!--<a class="lightbox" href="<?php echo $image; ?>" 
    rel="lightbox[rotation]" 
    title="<?php echo $maintitle ;?>"
    onclick="return false;"
><img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(357); ?>" alt="<?php echo $this->htmlEscape($_product->getImageLabel());?>"
/></a>-->

	
	<?php //} else { ?>
		
	<!--	
		<a class="lightbox" href="<?php echo $image; ?>" 
    rel="lightbox[rotation]" 
    title="<?php echo $maintitle ;?>"
    onclick="return false;"
><img  class="if-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>" alt="<?php echo $this->htmlEscape($_product->getImageLabel());?>" /></a>
		-->
		
		<?php //}; ?>
    
    
    



<?php else: ?>

<p class="product-image-zoom">
    <?php
        $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image')
    ?>
</p>
<p class="a-center" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>

<div class="image-zoom" id="track_outer">
    <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
    <div id="track">
        <div id="handle"></div>
    </div>
    <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
</div>
<script type="text/javascript">
    Event.observe(window, 'load', function() {
        product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    });
</script>

<?php endif; ?>

<script type="text/javascript">
//<![CDATA[
    //Event.observe(window, 'load', function() {
      //  product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
    //});
//]]>

    jQuery(document).ready(function() {
        jQuery(".additional_images1").click(function(){
            normal_image = jQuery(this).attr("normal-image");
            zoom_image = jQuery(this).attr("zoom-image");

            // alert(normal_image);
            // alert(zoom_image);

            jQuery("#zoom1").attr("href", zoom_image);
            jQuery("#zoom1 img").attr("src", normal_image);

            jQuery('.cloud-zoom').CloudZoom();
        });
    });
</script>





<?php if (count($this->getGalleryImages()) > 0): ?>

<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    	 
              <div id="slider2">
              <a class="buttons prev" href="#">left</a>
                <div class="viewport">
                    <ul class="overview">
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                    <?php
                    $subtitle = $this->htmlEscape($_image->getLabel());
                    if(($_lightboxConfig['productName'] != 0) && empty($subtitle)):
                            $subtitle  = $_product->getName();
                    endif;
                    ?>
                    <li>
                        
                        
                        <a class="additional_images" href="javascript:void(0);" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                <img class="additional_images1" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($additionalImageSize[0], $additionalImageSize[1]); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" zoom-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(700); ?>" normal-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(370); ?>" />
            </a>
                    </li>
                    <?php endforeach; ?>
                    </ul>
                  </div>
                   <a class="buttons next" href="#">right</a>
                </div>
</div>
<?php endif; ?>


<!--<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($popupImageSize[0], $popupImageSize[1]); ?>" 
            rel="lightbox[]" 
            title="<?php echo $subtitle; ?>"
            onclick="return false;"
        ><?php echo $this->__('HOVER TO ZOOM') ?></a>-->
        
        <a href="javascript:void(0);"><?php echo $this->__('HOVER TO ZOOM') ?></a>
        
        
        
        
<a class="fancyYoutube" href="<?php echo $videoLink; ?>">PLAY VIDEO</a>
<div class="social-product-page">
	<a class="twitter" href="https://twitter.com/AureliaSkincare" rel="external" target="_blank">Twitter</a>
	<a class="facebook" href="http://www.facebook.com/AureliaProbioticSkincare" rel="external" target="_blank">facebook</a>
    <a class="pinterest" href="http://pinterest.com/aureliaskincare/" rel="external" target="_blank">pinterest</a>
    <a class="mailing" href="mailto:info@aureliaskincare.com">aureliaskincare</a>
</div>


<script type="text/javascript">
function initLightbox(){
    new Lightbox({
        fileLoadingImage: '<?php echo $this->getSkinUrl('images/lightbox/loading.gif') ?>',
        fileBottomNavCloseImage: '<?php echo $this->getSkinUrl('images/lightbox/closelabel.gif') ?>',
        overlayOpacity: <?php echo $_lightboxConfig['overlayOpacity'] ?>,
        animate: <?php echo (($_lightboxConfig['animate'] > 0)? "1":"0"); ?>,
        resizeSpeed: <?php echo $_lightboxConfig['resizeSpeed'] ?>,
        borderSize: <?php echo $_lightboxConfig['borderSize'] ?>,
        labelImage: '<?php echo $_lightboxConfig['labelImage'] ?>',
        labelOf: '<?php echo $_lightboxConfig['labelOf'] ?>'
    });
}


if (Prototype.Browser.IE) {
    Event.observe(window, 'load', function(){ //KB927917 fix
        initLightbox();
    });
} else {
    document.observe("dom:loaded", function(){
        initLightbox();
    });
}
</script>

