<div id="onestepcheckout-login-popup" style="display: none;">
    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-contents">
            <div id="onestepcheckout-login-popup-contents-forgot" style="display: none;">
                <div class="popbox">
  <div class="popupinner"> <p class="close"><a href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('images/close-img-p.png',array(‘_secure’=>true)) ?>" width="20" height="20" alt=""/></a> </p>
   <img src="<?php echo $this->getSkinUrl('images/flower-img.jpg',array(‘_secure’=>true)) ?>" width="118" height="44" alt=""/>

                <h1><?php echo $this->__('Forgot your password?'); ?></h1>
                <p><?php echo $this->__('Please enter your email address below and we will send you a link to reset your password.'); ?></p>
                <div class="popupform">
                <form id="onestepcheckout-forgot-form">

                    <div id="onestepcheckout-forgot-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
                    <div id="onestepcheckout-forgot-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
                    <div id="onestepcheckout-forgot-success" style="display: none;">
                        <?php echo $this->__('We have now sent you a new password to your email address. Click the link below to return to login.'); ?>
                    </div>
                   <div id="onestepcheckout-forgot-table">
                        <label for="id_onestepcheckout_email"><?php echo $this->__('Email Address'); ?>*</label> 
                         <input type="text" class="input-text" name="onestepcheckout_email" id="id_onestepcheckout_email" />
                        <button id="onestepcheckout-forgot-button" type="button"><?php echo $this->__('SUBMIT'); ?></button>
                    </div>
                </form>
                <p style="margin-top: 10px;"><a href="javascript:void(0);" id="onestepcheckout-return-login-link"><?php echo $this->__('Return to Sign In'); ?></a></p>
                </div>
                
                </div>
                </div>
            </div>

            <div id="onestepcheckout-login-popup-contents-login">
            <div class="popbox">
            <div class="popupinner popupinner1 "> <p class="close"><a href="javascript:void(0);"><img src="<?php echo $this->getSkinUrl('images/close-img-p.png',array(‘_secure’=>true)) ?>" width="20" height="20" alt=""/></a> </p>
            <img src="<?php echo $this->getSkinUrl('images/flower-img.jpg',array(‘_secure’=>true)) ?>" width="118" height="44" alt=""/>

                <h1><?php echo $this->__('HELLO, PLEASE SIGN IN....'); ?></h1>
      

                <p><?php echo $this->__('To benefit from this offer please sign in to your Aurelia Loyalty account.')?></p>
                <div class="popupform">
                <form id="onestepcheckout-login-form">

                <div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
                <div id="onestepcheckout-login-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
                <div id="onestepcheckout-login-table">
                <label for="id_onestepcheckout_username"><?php echo $this->__('Email Address'); ?>*</label>
                <input tabindex="100" type="text" class="input-text" name="onestepcheckout_username" id="id_onestepcheckout_username" /></td>
                   <label for="id_onestepcheckout_password"><?php echo $this->__('Password'); ?>*</label>
                   <input type="password" tabindex="101" name="onestepcheckout_password" class="input-text" id="id_onestepcheckout_password" />
                    <button tabindex="102" id="onestepcheckout-login-button" type="button"><?php echo $this->__('SIGN IN'); ?></button>
                    <div>
                </form>
                 <a class="return-link" href="javascript:void(0);" id="onestepcheckout-forgot-password-link"><?php echo $this->__('Forgot your password?'); ?></a>
                </div>
                

                <div class="popupform dotbox" id="onestepcheckout-register-link" style="display:none;">
                   <h2 class="h2"><?php echo $this->__('Don’t have an account?')?></h2>
                    <span><?php echo $this->__('Love Aurelia Probiotic Skincare? To benefit from this offer and many more let us thank you');?>... 
                    </span>
                    <br/>
                    <a href="<?php echo $this->getUrl('customer/account/create')?>" class="join-btn"><?php echo $this->__('Join Aurelia Loyalty now')?></a>
                  </div> 



                    </div> <!--//popupinner popupinner1 -->
                </div> <!--//popbox -->
            </div>

            <!--p class="close"><a href="javascript:void(0);"><?php //echo $this->__('Close'); ?></a></p-->
        </div>
    </div>
    <!--div class="onestepcheckout-popup-footer">&nbsp;</div-->
</div>

<script>
var onestepcheckout_login_popup;
var login_popup;
Event.observe(window, 'load', function() {
    var options = {
        forgot_password_url: '<?php echo $this->getUrl('onestepcheckout/ajax/forgotPassword', array('_secure'=>true)); ?>',
        login_url: '<?php echo $this->getUrl('onestepcheckout/ajax/login', array('_secure'=>true)); ?>',
        translations: {
            invalid_email: '<?php echo $this->__('Please enter a valid email address'); ?>',
            email_not_found: '<?php echo $this->__('Please enter a registered email address.'); ?>'
        }
    };
    onestepcheckout_login_popup = new OneStepCheckoutLoginPopup(options);
    login_popup = onestepcheckout_login_popup;
});
</script>
